### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by surya-cn** [noob-hackers/ipdrone#11]
<--------------->
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/ipdrone/ipdrone.py", line 52, in <module>
    print (b, "[ISP]:", data['isp'])
KeyError: 'isp'

**Comment by Hasnain799** [comment]
How to fix this

**Comment by u0a377** [comment]
How to fix

**Comment by GreenWhiteWolf** [comment]
How to fix

**Comment by Charlydev777** [comment]
Como se arregla eso ??
