### ISSUE TITLE
KeyError  

### ISSUE THREAD

**Issue by newsdelhi10** [noob-hackers/ipdrone#21]
<--------------->
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/ipdrone/ipdrone.py", line 52, in <module>
    print (b, "[ISP]:", data['isp'])
KeyError: 'isp'

**Comment by Imango2518** [comment]
Same to me

**Comment by DavIoTech404** [comment]
if the api gets an error (probably cuz the IP is not public), the code doesn't handle the error and show this message, try to run with this IP: 142.251.129.46 or any other public.

127.0.0.1 doesn't works.
